import type { Product } from "./types";
import { PHOTOS, colorGalleries, gallery } from "./images";

/** Extra catalog entries — imported into PRODUCTS in catalog.ts */
export const CATALOG_ADDITIONS: Product[] = [
  // ─── Suits (+5) ───────────────────────────────────────
  {
    id: "44",
    slug: "piccadilly-linen-suit",
    name: "Piccadilly Linen Suit",
    description: "Unstructured two-piece in Irish linen with patch pockets for warm-weather tailoring.",
    gender: "men",
    category: "suits",
    subcategory: "two-piece",
    price: 3600,
    currency: "USD",
    images: gallery(PHOTOS.suitNavy2, PHOTOS.suitNavy3, PHOTOS.suitNavy4, PHOTOS.suitNavy5, PHOTOS.suitNavy6, PHOTOS.suitNavy1),
    colorImages: colorGalleries({
      navy: [PHOTOS.suitNavy2, PHOTOS.suitNavy3, PHOTOS.suitNavy4, PHOTOS.suitNavy5, PHOTOS.suitNavy6, PHOTOS.suitNavy1],
      cream: [PHOTOS.suitNavy4, PHOTOS.suitNavy3, PHOTOS.suitNavy2, PHOTOS.suitNavy1, PHOTOS.suitNavy5, PHOTOS.suitNavy6],
    }),
    colors: [
      { id: "navy", label: "Midnight Navy", value: "navy", inStock: true },
      { id: "cream", label: "Cream", value: "cream", inStock: true },
    ],
    sizes: ["38", "40", "42", "44", "46"].map((s) => ({ id: s, label: s, value: s, inStock: true })),
    variants: [],
    material: "Irish linen, horn buttons",
    care: "Dry clean only.",
    shippingNote: "Complimentary express delivery on orders over $500.",
    tags: ["suits", "new"],
    isNew: true,
  },
  {
    id: "45",
    slug: "regent-street-double-breasted",
    name: "Regent Street Double-Breasted",
    description: "Six-on-two double-breasted suit in chalk-stripe Super 130s wool.",
    gender: "men",
    category: "suits",
    subcategory: "two-piece",
    price: 4500,
    currency: "USD",
    images: gallery(PHOTOS.suitNavy1, PHOTOS.suitNavy4, PHOTOS.suitNavy5, PHOTOS.suitNavy6, PHOTOS.suitNavy2, PHOTOS.suitNavy3),
    colorImages: colorGalleries({
      charcoal: [PHOTOS.suitNavy1, PHOTOS.suitNavy4, PHOTOS.suitNavy5, PHOTOS.suitNavy6, PHOTOS.suitNavy2, PHOTOS.suitNavy3],
    }),
    colors: [{ id: "charcoal", label: "Charcoal", value: "charcoal", inStock: true }],
    sizes: ["38", "40", "42", "44", "46"].map((s) => ({ id: s, label: s, value: s, inStock: true })),
    variants: [],
    material: "Super 130s wool",
    care: "Dry clean only.",
    shippingNote: "Complimentary express delivery on orders over $500.",
    tags: ["suits"],
  },
  {
    id: "46",
    slug: "bond-street-dinner-jacket",
    name: "Bond Street Dinner Jacket",
    description: "Silk-shawl-collar dinner jacket in midnight barathea, sold separately.",
    gender: "men",
    category: "suits",
    subcategory: "tuxedo",
    price: 2800,
    currency: "USD",
    images: gallery(PHOTOS.tuxedo2, PHOTOS.tuxedo3, PHOTOS.tuxedo4, PHOTOS.tuxedo1, PHOTOS.suitNavy1, PHOTOS.suitNavy2),
    colorImages: colorGalleries({
      black: [PHOTOS.tuxedo2, PHOTOS.tuxedo3, PHOTOS.tuxedo4, PHOTOS.tuxedo1, PHOTOS.suitNavy1, PHOTOS.suitNavy2],
    }),
    colors: [{ id: "black", label: "Black", value: "black", inStock: true }],
    sizes: ["38", "40", "42", "44", "46"].map((s) => ({ id: s, label: s, value: s, inStock: true })),
    variants: [],
    material: "Barathea wool, silk facings",
    care: "Dry clean only.",
    shippingNote: "Complimentary express delivery on orders over $500.",
    tags: ["evening"],
  },
  {
    id: "47",
    slug: "kensington-herringbone-blazer",
    name: "Kensington Herringbone Blazer",
    description: "Soft-shouldered blazer in English herringbone with horn buttons.",
    gender: "women",
    category: "suits",
    subcategory: "blazer",
    price: 2200,
    currency: "USD",
    images: gallery(PHOTOS.blazerW1, PHOTOS.blazerW2, PHOTOS.blazerW3, PHOTOS.suitNavy3, PHOTOS.suitNavy4, PHOTOS.suitNavy5),
    colorImages: colorGalleries({
      navy: [PHOTOS.blazerW1, PHOTOS.blazerW2, PHOTOS.blazerW3, PHOTOS.suitNavy3, PHOTOS.suitNavy4, PHOTOS.suitNavy5],
    }),
    colors: [{ id: "navy", label: "Midnight Navy", value: "navy", inStock: true }],
    sizes: ["34", "36", "38", "40", "42"].map((s) => ({ id: s, label: s, value: s, inStock: true })),
    variants: [],
    material: "Wool herringbone",
    care: "Dry clean only.",
    shippingNote: "Complimentary express delivery on orders over $500.",
    tags: ["suits", "new"],
    isNew: true,
  },
  {
    id: "48",
    slug: "junior-row-short-suit",
    name: "Junior Row Short Suit",
    description: "Single-breasted short suit for formal occasions, cut with growing room.",
    gender: "kids",
    category: "suits",
    subcategory: "two-piece",
    price: 680,
    currency: "USD",
    images: gallery(PHOTOS.kidsBlazer1, PHOTOS.kidsBlazer2, PHOTOS.kidsPromo, PHOTOS.suitNavy1, PHOTOS.suitNavy2, PHOTOS.suitNavy3),
    colorImages: colorGalleries({
      navy: [PHOTOS.kidsBlazer1, PHOTOS.kidsBlazer2, PHOTOS.kidsPromo, PHOTOS.suitNavy1, PHOTOS.suitNavy2, PHOTOS.suitNavy3],
    }),
    colors: [{ id: "navy", label: "Midnight Navy", value: "navy", inStock: true }],
    sizes: ["6", "8", "10", "12", "14"].map((s) => ({ id: s, label: `Age ${s}`, value: s, inStock: true })),
    variants: [],
    material: "Wool blend",
    care: "Dry clean only.",
    shippingNote: "Complimentary express delivery on orders over $500.",
    tags: ["kids"],
  },
  // ─── Shoes (+5) ───────────────────────────────────────
  {
    id: "49",
    slug: "pall-mall-monk-strap",
    name: "Pall Mall Double Monk",
    description: "Hand-burnished double monk strap on leather sole with cap toe.",
    gender: "men",
    category: "shoes",
    subcategory: "oxford",
    price: 920,
    currency: "USD",
    images: gallery(PHOTOS.oxfordBlack1, PHOTOS.oxfordBlack2, PHOTOS.oxfordBlack3, PHOTOS.oxfordBlack4, PHOTOS.oxfordBurgundy1, PHOTOS.oxfordBurgundy2),
    colorImages: colorGalleries({
      black: [PHOTOS.oxfordBlack1, PHOTOS.oxfordBlack2, PHOTOS.oxfordBlack3, PHOTOS.oxfordBlack4, PHOTOS.oxfordBurgundy1, PHOTOS.oxfordBurgundy2],
      burgundy: [PHOTOS.oxfordBurgundy1, PHOTOS.oxfordBurgundy2, PHOTOS.oxfordBlack3, PHOTOS.oxfordBlack4, PHOTOS.oxfordBlack1, PHOTOS.oxfordBlack2],
    }),
    colors: [
      { id: "black", label: "Black", value: "black", inStock: true },
      { id: "burgundy", label: "Burgundy", value: "burgundy", inStock: true },
    ],
    sizes: ["39", "40", "41", "42", "43", "44", "45"].map((s) => ({ id: s, label: s, value: s, inStock: true })),
    variants: [],
    material: "Calfskin, leather sole",
    care: "Use shoe trees. Polish monthly.",
    shippingNote: "Complimentary express delivery on orders over $500.",
    tags: ["shoes", "new"],
    isNew: true,
  },
  {
    id: "50",
    slug: "st-james-tassel-loafer",
    name: "St James Tassel Loafer",
    description: "Full-grain tassel loafer with hand-stitched apron and leather sole.",
    gender: "men",
    category: "shoes",
    subcategory: "loafer",
    price: 820,
    currency: "USD",
    images: gallery(PHOTOS.loafer1, PHOTOS.loafer2, PHOTOS.loafer3, PHOTOS.loafer2, PHOTOS.loafer1, PHOTOS.loafer3),
    colorImages: colorGalleries({
      burgundy: [PHOTOS.loafer1, PHOTOS.loafer2, PHOTOS.loafer3, PHOTOS.loafer2, PHOTOS.loafer1, PHOTOS.loafer3],
      black: [PHOTOS.loafer2, PHOTOS.loafer3, PHOTOS.loafer1, PHOTOS.loafer3, PHOTOS.loafer2, PHOTOS.loafer1],
    }),
    colors: [
      { id: "burgundy", label: "Burgundy", value: "burgundy", inStock: true },
      { id: "black", label: "Black", value: "black", inStock: true },
    ],
    sizes: ["39", "40", "41", "42", "43", "44", "45"].map((s) => ({ id: s, label: s, value: s, inStock: true })),
    variants: [],
    material: "Full-grain leather",
    care: "Brush and condition monthly.",
    shippingNote: "Complimentary express delivery on orders over $500.",
    tags: ["shoes"],
  },
  {
    id: "51",
    slug: "covent-garden-derby-boot",
    name: "Covent Garden Derby Boot",
    description: "Cap-toe derby boot in polished calfskin with storm welt.",
    gender: "men",
    category: "shoes",
    subcategory: "chelsea-boot",
    price: 1050,
    currency: "USD",
    images: gallery(PHOTOS.oxfordBlack4, PHOTOS.oxfordBlack3, PHOTOS.oxfordBlack2, PHOTOS.oxfordBlack1, PHOTOS.oxfordBlack3, PHOTOS.oxfordBlack4),
    colorImages: colorGalleries({
      black: [PHOTOS.oxfordBlack4, PHOTOS.oxfordBlack3, PHOTOS.oxfordBlack2, PHOTOS.oxfordBlack1, PHOTOS.oxfordBlack3, PHOTOS.oxfordBlack4],
    }),
    colors: [{ id: "black", label: "Black", value: "black", inStock: true }],
    sizes: ["39", "40", "41", "42", "43", "44", "45"].map((s) => ({ id: s, label: s, value: s, inStock: true })),
    variants: [],
    material: "Calfskin, Goodyear welt",
    care: "Use shoe trees.",
    shippingNote: "Complimentary express delivery on orders over $500.",
    tags: ["shoes"],
  },
  {
    id: "52",
    slug: "south-bank-espadrille",
    name: "South Bank Espadrille",
    description: "Hand-stitched espadrille in woven canvas with leather trim.",
    gender: "women",
    category: "shoes",
    subcategory: "sandal",
    price: 480,
    currency: "USD",
    images: gallery(PHOTOS.pump1, PHOTOS.pump2, PHOTOS.pump1, PHOTOS.pump2, PHOTOS.pump1, PHOTOS.pump2),
    colorImages: colorGalleries({
      cream: [PHOTOS.pump1, PHOTOS.pump2, PHOTOS.pump1, PHOTOS.pump2, PHOTOS.pump1, PHOTOS.pump2],
      black: [PHOTOS.pump2, PHOTOS.pump1, PHOTOS.pump2, PHOTOS.pump1, PHOTOS.pump2, PHOTOS.pump1],
    }),
    colors: [
      { id: "cream", label: "Cream", value: "cream", inStock: true },
      { id: "black", label: "Black", value: "black", inStock: true },
    ],
    sizes: ["36", "37", "38", "39", "40"].map((s) => ({ id: s, label: s, value: s, inStock: true })),
    variants: [],
    material: "Canvas, jute sole",
    care: "Spot clean only.",
    shippingNote: "Complimentary express delivery on orders over $500.",
    tags: ["shoes", "new"],
    isNew: true,
  },
  {
    id: "53",
    slug: "hyde-park-pump",
    name: "Hyde Park 85mm Pump",
    description: "Classic pointed pump in patent calfskin with signature red leather sole.",
    gender: "women",
    category: "shoes",
    subcategory: "pump",
    price: 795,
    currency: "USD",
    images: gallery(PHOTOS.pump1, PHOTOS.pump2, PHOTOS.pump1, PHOTOS.pump2, PHOTOS.pump1, PHOTOS.pump2),
    colorImages: colorGalleries({
      black: [PHOTOS.pump1, PHOTOS.pump2, PHOTOS.pump1, PHOTOS.pump2, PHOTOS.pump1, PHOTOS.pump2],
      burgundy: [PHOTOS.pump2, PHOTOS.pump1, PHOTOS.pump2, PHOTOS.pump1, PHOTOS.pump2, PHOTOS.pump1],
    }),
    colors: [
      { id: "black", label: "Black", value: "black", inStock: true },
      { id: "burgundy", label: "Burgundy", value: "burgundy", inStock: true },
    ],
    sizes: ["36", "37", "38", "39", "40"].map((s) => ({ id: s, label: s, value: s, inStock: true })),
    variants: [],
    material: "Patent calfskin",
    care: "Wipe with soft cloth.",
    shippingNote: "Complimentary express delivery on orders over $500.",
    tags: ["shoes"],
  },
  // ─── Bags (+5) ────────────────────────────────────────
  {
    id: "54",
    slug: "green-park-messenger",
    name: "Green Park Messenger",
    description: "Cross-grain leather messenger with adjustable strap and interior laptop sleeve.",
    gender: "men",
    category: "bags",
    subcategory: "crossbody",
    price: 1280,
    currency: "USD",
    images: gallery(PHOTOS.bagWeekender1, PHOTOS.bagWeekender2, PHOTOS.bagWeekender3, PHOTOS.bagWeekender2, PHOTOS.bagWeekender1, PHOTOS.bagWeekender3),
    colorImages: colorGalleries({
      navy: [PHOTOS.bagWeekender1, PHOTOS.bagWeekender2, PHOTOS.bagWeekender3, PHOTOS.bagWeekender2, PHOTOS.bagWeekender1, PHOTOS.bagWeekender3],
      black: [PHOTOS.bagWeekender2, PHOTOS.bagWeekender3, PHOTOS.bagWeekender1, PHOTOS.bagWeekender3, PHOTOS.bagWeekender2, PHOTOS.bagWeekender1],
    }),
    colors: [
      { id: "navy", label: "Midnight Navy", value: "navy", inStock: true },
      { id: "black", label: "Black", value: "black", inStock: true },
    ],
    sizes: [{ id: "os", label: "One Size", value: "OS", inStock: true }],
    variants: [],
    material: "Grained calf leather",
    care: "Condition seasonally.",
    shippingNote: "Complimentary express delivery on orders over $500.",
    tags: ["bags"],
  },
  {
    id: "55",
    slug: "chelsea-document-case",
    name: "Chelsea Document Case",
    description: "Slim document case with twin handles and detachable shoulder strap.",
    gender: "men",
    category: "bags",
    subcategory: "briefcase",
    price: 1650,
    currency: "USD",
    images: gallery(PHOTOS.bagWeekender3, PHOTOS.bagWeekender2, PHOTOS.bagWeekender1, PHOTOS.bagWeekender3, PHOTOS.bagWeekender2, PHOTOS.bagWeekender1),
    colorImages: colorGalleries({
      black: [PHOTOS.bagWeekender3, PHOTOS.bagWeekender2, PHOTOS.bagWeekender1, PHOTOS.bagWeekender3, PHOTOS.bagWeekender2, PHOTOS.bagWeekender1],
    }),
    colors: [{ id: "black", label: "Black", value: "black", inStock: true }],
    sizes: [{ id: "os", label: "One Size", value: "OS", inStock: true }],
    variants: [],
    material: "Bridle leather",
    care: "Condition twice yearly.",
    shippingNote: "Complimentary express delivery on orders over $500.",
    tags: ["bags", "new"],
    isNew: true,
  },
  {
    id: "56",
    slug: "mayfair-evening-clutch",
    name: "Mayfair Evening Minaudière",
    description: "Hard-case evening clutch with chain strap and silk interior.",
    gender: "women",
    category: "bags",
    subcategory: "clutch",
    price: 980,
    currency: "USD",
    images: gallery(PHOTOS.clutch1, PHOTOS.clutch2, PHOTOS.clutch3, PHOTOS.clutch2, PHOTOS.clutch1, PHOTOS.clutch3),
    colorImages: colorGalleries({
      gold: [PHOTOS.clutch1, PHOTOS.clutch2, PHOTOS.clutch3, PHOTOS.clutch2, PHOTOS.clutch1, PHOTOS.clutch3],
      black: [PHOTOS.clutch2, PHOTOS.clutch3, PHOTOS.clutch1, PHOTOS.clutch3, PHOTOS.clutch2, PHOTOS.clutch1],
    }),
    colors: [
      { id: "gold", label: "Antique Gold", value: "gold", inStock: true },
      { id: "black", label: "Black", value: "black", inStock: true },
    ],
    sizes: [{ id: "os", label: "One Size", value: "OS", inStock: true }],
    variants: [],
    material: "Metal frame, silk lining",
    care: "Store in dust bag.",
    shippingNote: "Complimentary express delivery on orders over $500.",
    tags: ["bags"],
  },
  {
    id: "57",
    slug: "richmond-travel-backpack",
    name: "Richmond Travel Backpack",
    description: "Roll-top backpack in water-resistant canvas with leather base.",
    gender: "men",
    category: "bags",
    subcategory: "backpack",
    price: 1120,
    currency: "USD",
    images: gallery(PHOTOS.bagWeekender2, PHOTOS.bagWeekender1, PHOTOS.bagWeekender3, PHOTOS.bagWeekender1, PHOTOS.bagWeekender2, PHOTOS.bagWeekender3),
    colorImages: colorGalleries({
      navy: [PHOTOS.bagWeekender2, PHOTOS.bagWeekender1, PHOTOS.bagWeekender3, PHOTOS.bagWeekender1, PHOTOS.bagWeekender2, PHOTOS.bagWeekender3],
    }),
    colors: [{ id: "navy", label: "Midnight Navy", value: "navy", inStock: true }],
    sizes: [{ id: "os", label: "One Size", value: "OS", inStock: true }],
    variants: [],
    material: "Waxed canvas, leather trim",
    care: "Brush canvas; condition leather.",
    shippingNote: "Complimentary express delivery on orders over $500.",
    tags: ["bags"],
  },
  {
    id: "58",
    slug: "notting-hill-mini-tote",
    name: "Notting Hill Mini Tote",
    description: "Compact structured tote with top handles and removable strap.",
    gender: "women",
    category: "bags",
    subcategory: "tote",
    price: 1350,
    currency: "USD",
    images: gallery(PHOTOS.bagWeekender1, PHOTOS.bagWeekender3, PHOTOS.bagWeekender2, PHOTOS.bagWeekender3, PHOTOS.bagWeekender1, PHOTOS.bagWeekender2),
    colorImages: colorGalleries({
      cream: [PHOTOS.bagWeekender1, PHOTOS.bagWeekender3, PHOTOS.bagWeekender2, PHOTOS.bagWeekender3, PHOTOS.bagWeekender1, PHOTOS.bagWeekender2],
      black: [PHOTOS.bagWeekender3, PHOTOS.bagWeekender2, PHOTOS.bagWeekender1, PHOTOS.bagWeekender2, PHOTOS.bagWeekender3, PHOTOS.bagWeekender1],
    }),
    colors: [
      { id: "cream", label: "Cream", value: "cream", inStock: true },
      { id: "black", label: "Black", value: "black", inStock: true },
    ],
    sizes: [{ id: "os", label: "One Size", value: "OS", inStock: true }],
    variants: [],
    material: "Calf leather",
    care: "Condition seasonally.",
    shippingNote: "Complimentary express delivery on orders over $500.",
    tags: ["bags", "new"],
    isNew: true,
  },
  // ─── Perfumes (+5) ────────────────────────────────────
  {
    id: "59",
    slug: "mayfair-oud",
    name: "Mayfair Oud",
    description: "Woody oriental with Assam oud, rose, and smoked vetiver.",
    gender: "men",
    category: "perfumes",
    subcategory: "eau-de-parfum",
    price: 320,
    currency: "USD",
    images: gallery(PHOTOS.perfume1, PHOTOS.perfume2, PHOTOS.perfume3, PHOTOS.perfume2, PHOTOS.perfume1, PHOTOS.perfume3),
    colorImages: colorGalleries({
      clear: [PHOTOS.perfume1, PHOTOS.perfume2, PHOTOS.perfume3, PHOTOS.perfume2, PHOTOS.perfume1, PHOTOS.perfume3],
    }),
    colors: [{ id: "clear", label: "Clear", value: "clear", inStock: true }],
    sizes: [{ id: "50", label: "50 ml", value: "50", inStock: true }, { id: "100", label: "100 ml", value: "100", inStock: true }],
    variants: [],
    material: "Eau de parfum",
    care: "Store away from light.",
    shippingNote: "Complimentary express delivery on orders over $500.",
    tags: ["perfumes"],
  },
  {
    id: "60",
    slug: "savile-cologne",
    name: "Savile Cologne",
    description: "Bright cologne of bergamot, neroli, and white musk.",
    gender: "men",
    category: "perfumes",
    subcategory: "cologne",
    price: 195,
    currency: "USD",
    images: gallery(PHOTOS.cologne1, PHOTOS.cologne2, PHOTOS.cologne1, PHOTOS.cologne2, PHOTOS.cologne1, PHOTOS.cologne2),
    colorImages: colorGalleries({
      clear: [PHOTOS.cologne1, PHOTOS.cologne2, PHOTOS.cologne1, PHOTOS.cologne2, PHOTOS.cologne1, PHOTOS.cologne2],
    }),
    colors: [{ id: "clear", label: "Clear", value: "clear", inStock: true }],
    sizes: [{ id: "100", label: "100 ml", value: "100", inStock: true }],
    variants: [],
    material: "Cologne",
    care: "Store away from heat.",
    shippingNote: "Complimentary express delivery on orders over $500.",
    tags: ["perfumes", "new"],
    isNew: true,
  },
  {
    id: "61",
    slug: "rose-mayfair-edt",
    name: "Rose Mayfair",
    description: "Floral eau de toilette with May rose, peony, and sandalwood.",
    gender: "women",
    category: "perfumes",
    subcategory: "eau-de-toilette",
    price: 240,
    currency: "USD",
    images: gallery(PHOTOS.perfume2, PHOTOS.perfume3, PHOTOS.perfume1, PHOTOS.perfume3, PHOTOS.perfume2, PHOTOS.perfume1),
    colorImages: colorGalleries({
      clear: [PHOTOS.perfume2, PHOTOS.perfume3, PHOTOS.perfume1, PHOTOS.perfume3, PHOTOS.perfume2, PHOTOS.perfume1],
    }),
    colors: [{ id: "clear", label: "Clear", value: "clear", inStock: true }],
    sizes: [{ id: "50", label: "50 ml", value: "50", inStock: true }, { id: "100", label: "100 ml", value: "100", inStock: true }],
    variants: [],
    material: "Eau de toilette",
    care: "Store away from light.",
    shippingNote: "Complimentary express delivery on orders over $500.",
    tags: ["perfumes"],
  },
  {
    id: "62",
    slug: "no17-extrait",
    name: "No. 17 Extrait",
    description: "Concentrated extrait of iris, leather, and ambergris accord.",
    gender: "women",
    category: "perfumes",
    subcategory: "extrait",
    price: 480,
    currency: "USD",
    images: gallery(PHOTOS.perfume3, PHOTOS.perfume1, PHOTOS.perfume2, PHOTOS.perfume1, PHOTOS.perfume3, PHOTOS.perfume2),
    colorImages: colorGalleries({
      clear: [PHOTOS.perfume3, PHOTOS.perfume1, PHOTOS.perfume2, PHOTOS.perfume1, PHOTOS.perfume3, PHOTOS.perfume2],
    }),
    colors: [{ id: "clear", label: "Clear", value: "clear", inStock: true }],
    sizes: [{ id: "30", label: "30 ml", value: "30", inStock: true }],
    variants: [],
    material: "Extrait de parfum",
    care: "Store in original box.",
    shippingNote: "Complimentary express delivery on orders over $500.",
    tags: ["perfumes"],
  },
  {
    id: "63",
    slug: "row-vetiver",
    name: "Row Vetiver",
    description: "Dry vetiver and cedarwood composition with a hint of grapefruit.",
    gender: "men",
    category: "perfumes",
    subcategory: "eau-de-parfum",
    price: 285,
    currency: "USD",
    images: gallery(PHOTOS.perfume1, PHOTOS.perfume3, PHOTOS.perfume2, PHOTOS.perfume3, PHOTOS.perfume1, PHOTOS.perfume2),
    colorImages: colorGalleries({
      clear: [PHOTOS.perfume1, PHOTOS.perfume3, PHOTOS.perfume2, PHOTOS.perfume3, PHOTOS.perfume1, PHOTOS.perfume2],
    }),
    colors: [{ id: "clear", label: "Clear", value: "clear", inStock: true }],
    sizes: [{ id: "50", label: "50 ml", value: "50", inStock: true }, { id: "100", label: "100 ml", value: "100", inStock: true }],
    variants: [],
    material: "Eau de parfum",
    care: "Store away from light.",
    shippingNote: "Complimentary express delivery on orders over $500.",
    tags: ["perfumes", "new"],
    isNew: true,
  },
  // ─── Accessories (+5) ─────────────────────────────────
  {
    id: "64",
    slug: "silk-grenadine-tie",
    name: "Silk Grenadine Tie",
    description: "Hand-rolled grenadine tie in Italian silk with wool interlining.",
    gender: "men",
    category: "accessories",
    subcategory: "tie",
    price: 195,
    currency: "USD",
    images: gallery(PHOTOS.cufflinks1, PHOTOS.cufflinks2, PHOTOS.cufflinks3, PHOTOS.cufflinks2, PHOTOS.cufflinks1, PHOTOS.cufflinks3),
    colorImages: colorGalleries({
      navy: [PHOTOS.cufflinks1, PHOTOS.cufflinks2, PHOTOS.cufflinks3, PHOTOS.cufflinks2, PHOTOS.cufflinks1, PHOTOS.cufflinks3],
      burgundy: [PHOTOS.cufflinks2, PHOTOS.cufflinks3, PHOTOS.cufflinks1, PHOTOS.cufflinks3, PHOTOS.cufflinks2, PHOTOS.cufflinks1],
    }),
    colors: [
      { id: "navy", label: "Midnight Navy", value: "navy", inStock: true },
      { id: "burgundy", label: "Burgundy", value: "burgundy", inStock: true },
    ],
    sizes: [{ id: "os", label: "One Size", value: "OS", inStock: true }],
    variants: [],
    material: "Italian silk",
    care: "Dry clean only.",
    shippingNote: "Complimentary express delivery on orders over $500.",
    tags: ["accessories"],
  },
  {
    id: "65",
    slug: "cashmere-scarf-charcoal",
    name: "Cashmere Scarf",
    description: "Lightweight cashmere scarf woven in the Scottish Borders.",
    gender: "women",
    category: "accessories",
    subcategory: "scarf",
    price: 420,
    currency: "USD",
    images: gallery(PHOTOS.cufflinks3, PHOTOS.cufflinks2, PHOTOS.cufflinks1, PHOTOS.cufflinks2, PHOTOS.cufflinks3, PHOTOS.cufflinks1),
    colorImages: colorGalleries({
      charcoal: [PHOTOS.cufflinks3, PHOTOS.cufflinks2, PHOTOS.cufflinks1, PHOTOS.cufflinks2, PHOTOS.cufflinks3, PHOTOS.cufflinks1],
      cream: [PHOTOS.cufflinks2, PHOTOS.cufflinks1, PHOTOS.cufflinks3, PHOTOS.cufflinks1, PHOTOS.cufflinks2, PHOTOS.cufflinks3],
    }),
    colors: [
      { id: "charcoal", label: "Charcoal", value: "charcoal", inStock: true },
      { id: "cream", label: "Cream", value: "cream", inStock: true },
    ],
    sizes: [{ id: "os", label: "One Size", value: "OS", inStock: true }],
    variants: [],
    material: "Cashmere",
    care: "Dry clean or hand wash cold.",
    shippingNote: "Complimentary express delivery on orders over $500.",
    tags: ["accessories", "new"],
    isNew: true,
  },
  {
    id: "66",
    slug: "silk-pocket-square-set",
    name: "Silk Pocket Square Set",
    description: "Set of three hand-rolled silk pocket squares in seasonal prints.",
    gender: "men",
    category: "accessories",
    subcategory: "pocket-square",
    price: 285,
    currency: "USD",
    images: gallery(PHOTOS.cufflinks1, PHOTOS.cufflinks3, PHOTOS.cufflinks2, PHOTOS.cufflinks1, PHOTOS.cufflinks3, PHOTOS.cufflinks2),
    colorImages: colorGalleries({
      navy: [PHOTOS.cufflinks1, PHOTOS.cufflinks3, PHOTOS.cufflinks2, PHOTOS.cufflinks1, PHOTOS.cufflinks3, PHOTOS.cufflinks2],
    }),
    colors: [{ id: "navy", label: "Midnight Navy", value: "navy", inStock: true }],
    sizes: [{ id: "os", label: "One Size", value: "OS", inStock: true }],
    variants: [],
    material: "Silk",
    care: "Dry clean only.",
    shippingNote: "Complimentary express delivery on orders over $500.",
    tags: ["accessories"],
  },
  {
    id: "67",
    slug: "sterling-cufflinks",
    name: "Sterling Enamel Cufflinks",
    description: "Sterling silver cufflinks with hand-applied enamel in House colours.",
    gender: "men",
    category: "accessories",
    subcategory: "cufflinks",
    price: 395,
    currency: "USD",
    images: gallery(PHOTOS.cufflinks1, PHOTOS.cufflinks2, PHOTOS.cufflinks3, PHOTOS.cufflinks1, PHOTOS.cufflinks2, PHOTOS.cufflinks3),
    colorImages: colorGalleries({
      gold: [PHOTOS.cufflinks1, PHOTOS.cufflinks2, PHOTOS.cufflinks3, PHOTOS.cufflinks1, PHOTOS.cufflinks2, PHOTOS.cufflinks3],
      navy: [PHOTOS.cufflinks2, PHOTOS.cufflinks3, PHOTOS.cufflinks1, PHOTOS.cufflinks2, PHOTOS.cufflinks3, PHOTOS.cufflinks1],
    }),
    colors: [
      { id: "gold", label: "Antique Gold", value: "gold", inStock: true },
      { id: "navy", label: "Midnight Navy", value: "navy", inStock: true },
    ],
    sizes: [{ id: "os", label: "One Size", value: "OS", inStock: true }],
    variants: [],
    material: "Sterling silver, enamel",
    care: "Polish with soft cloth.",
    shippingNote: "Complimentary express delivery on orders over $500.",
    tags: ["accessories"],
  },
  {
    id: "68",
    slug: "card-holder-calf",
    name: "Calfskin Card Holder",
    description: "Six-slot card holder in smooth calfskin with contrast stitching.",
    gender: "men",
    category: "accessories",
    subcategory: "wallets",
    price: 245,
    currency: "USD",
    images: gallery(PHOTOS.wallet1, PHOTOS.wallet2, PHOTOS.wallet3, PHOTOS.wallet2, PHOTOS.wallet1, PHOTOS.wallet3),
    colorImages: colorGalleries({
      black: [PHOTOS.wallet1, PHOTOS.wallet2, PHOTOS.wallet3, PHOTOS.wallet2, PHOTOS.wallet1, PHOTOS.wallet3],
      burgundy: [PHOTOS.wallet2, PHOTOS.wallet3, PHOTOS.wallet1, PHOTOS.wallet3, PHOTOS.wallet2, PHOTOS.wallet1],
    }),
    colors: [
      { id: "black", label: "Black", value: "black", inStock: true },
      { id: "burgundy", label: "Burgundy", value: "burgundy", inStock: true },
    ],
    sizes: [{ id: "os", label: "One Size", value: "OS", inStock: true }],
    variants: [],
    material: "Calfskin",
    care: "Condition occasionally.",
    shippingNote: "Complimentary express delivery on orders over $500.",
    tags: ["accessories", "new"],
    isNew: true,
  },
];
