import type { Gender, Product, ProductCategory } from "./types";
import { CATALOG_ADDITIONS } from "./catalog-additions";
import { PHOTOS, colorGalleries, gallery } from "./images";
import { applyProductImages } from "./product-images";

function makeVariants(
  sizes: string[],
  colors: { id: string; label: string; value: string }[]
) {
  const variants = [];
  let i = 0;
  for (const size of sizes) {
    for (const color of colors) {
      // Deterministic stock: ~2 sizes per colour run show as sold out
      const inStock = i % 5 !== 2 && i % 7 !== 4;
      variants.push({
        id: `${size}-${color.id}`,
        sku: `SR-${size}-${color.id}`.toUpperCase(),
        size,
        color: color.value,
        priceModifier: 0,
        inStock,
      });
      i += 1;
    }
  }
  return variants;
}

const COLORS = {
  navy: { id: "navy", label: "Midnight Navy", value: "navy", inStock: true },
  charcoal: { id: "charcoal", label: "Charcoal", value: "charcoal", inStock: true },
  cream: { id: "cream", label: "Cream", value: "cream", inStock: true },
  gold: { id: "gold", label: "Antique Gold", value: "gold", inStock: true },
  black: { id: "black", label: "Black", value: "black", inStock: true },
  burgundy: { id: "burgundy", label: "Burgundy", value: "burgundy", inStock: true },
};

const SIZES_SUIT = ["36", "38", "40", "42", "44", "46"];
const SIZES_SHOE = ["38", "39", "40", "41", "42", "43", "44", "45", "46"];
const SHOE_SIZE_OPTIONS = SIZES_SHOE.map((s) => ({
  id: s,
  label: `EU ${s}`,
  value: s,
  inStock: true,
}));
const SIZES_STD = ["XS", "S", "M", "L", "XL"];

const DEFAULT_SHIPPING =
  "Complimentary express delivery on orders over $500. International duties may apply.";

export const PRODUCTS: Product[] = [
  {
    id: "1",
    slug: "mayfair-two-piece",
    name: "Mayfair Two-Piece Suit",
    description:
      "Hand-finished two-piece in Super 150s wool. Soft shoulder, natural lapel roll, half-canvas construction.",
    gender: "men",
    category: "suits",
    subcategory: "two-piece",
    price: 4200,
    currency: "USD",
    images: gallery(
      PHOTOS.suitNavy1,
      PHOTOS.suitNavy2,
      PHOTOS.suitNavy3,
      PHOTOS.suitNavy4,
      PHOTOS.suitNavy5,
      PHOTOS.suitNavy6
    ),
    colorImages: colorGalleries({
      navy: [
        PHOTOS.suitNavy1,
        PHOTOS.suitNavy2,
        PHOTOS.suitNavy3,
        PHOTOS.suitNavy4,
        PHOTOS.suitNavy5,
        PHOTOS.suitNavy6,
      ],
      charcoal: [
        PHOTOS.suitNavy4,
        PHOTOS.suitNavy3,
        PHOTOS.suitNavy2,
        PHOTOS.suitNavy1,
        PHOTOS.suitNavy5,
        PHOTOS.suitNavy6,
      ],
    }),
    colors: [COLORS.navy, COLORS.charcoal],
    sizes: SIZES_SUIT.map((s) => ({ id: s, label: s, value: s, inStock: true })),
    variants: makeVariants(SIZES_SUIT, [COLORS.navy, COLORS.charcoal]),
    material: "Super 150s wool, cupro lining, horn buttons",
    care: "Dry clean only. Store on a shaped hanger.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["bespoke", "new"],
    isNew: true,
    isBespokeEligible: true,
  },
  {
    id: "2",
    slug: "st-james-morning-coat",
    name: "St James Morning Coat",
    description: "Formal morning coat with silk-faced lapels for Royal Ascot and white-tie occasions.",
    gender: "men",
    category: "suits",
    subcategory: "morning-coat",
    price: 5800,
    currency: "USD",
    images: gallery(
      PHOTOS.morningCoat1,
      PHOTOS.morningCoat2,
      PHOTOS.morningCoat3,
      PHOTOS.morningCoat4,
      PHOTOS.suitNavy5,
      PHOTOS.suitNavy6
    ),
    colorImages: colorGalleries({
      black: [
        PHOTOS.morningCoat1,
        PHOTOS.morningCoat2,
        PHOTOS.morningCoat3,
        PHOTOS.morningCoat4,
        PHOTOS.suitNavy5,
        PHOTOS.suitNavy6,
      ],
    }),
    colors: [COLORS.black],
    sizes: SIZES_SUIT.map((s) => ({ id: s, label: s, value: s, inStock: true })),
    variants: makeVariants(["38", "40", "42", "44"], [COLORS.black]),
    material: "Barathea wool, silk facings",
    care: "Dry clean only. Brush after wear.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["formal"],
    isBespokeEligible: true,
  },
  {
    id: "3",
    slug: "chelsea-tuxedo",
    name: "Chelsea Peak-Lapel Tuxedo",
    description: "Single-button peak lapel dinner suit in barathea wool with satin facings.",
    gender: "men",
    category: "suits",
    subcategory: "tuxedo",
    price: 3900,
    currency: "USD",
    images: gallery(
      PHOTOS.tuxedo1,
      PHOTOS.tuxedo2,
      PHOTOS.tuxedo3,
      PHOTOS.tuxedo4,
      PHOTOS.suitNavy1,
      PHOTOS.suitNavy2
    ),
    colorImages: colorGalleries({
      black: [
        PHOTOS.tuxedo1,
        PHOTOS.tuxedo2,
        PHOTOS.tuxedo3,
        PHOTOS.tuxedo4,
        PHOTOS.suitNavy1,
        PHOTOS.suitNavy2,
      ],
    }),
    colors: [COLORS.black],
    sizes: SIZES_SUIT.map((s) => ({ id: s, label: s, value: s, inStock: true })),
    variants: makeVariants(SIZES_SUIT, [COLORS.black]),
    material: "Barathea wool, satin lapels",
    care: "Dry clean only.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["evening"],
    isBespokeEligible: true,
  },
  {
    id: "4",
    slug: "connaught-oxford",
    name: "Connaught Cap-Toe Oxford",
    description: "Hand-burnished calfskin oxford on leather sole. Goodyear welted in Northampton.",
    gender: "men",
    category: "shoes",
    subcategory: "oxford",
    price: 890,
    currency: "USD",
    images: gallery(
      PHOTOS.oxfordBlack1,
      PHOTOS.oxfordBlack2,
      PHOTOS.oxfordBlack3,
      PHOTOS.oxfordBlack4,
      PHOTOS.oxfordBurgundy1,
      PHOTOS.oxfordBurgundy2
    ),
    colorImages: colorGalleries({
      black: [
        PHOTOS.oxfordBlack1,
        PHOTOS.oxfordBlack2,
        PHOTOS.oxfordBlack3,
        PHOTOS.oxfordBlack4,
        PHOTOS.oxfordBlack3,
        PHOTOS.oxfordBlack2,
      ],
      burgundy: [
        PHOTOS.oxfordBurgundy1,
        PHOTOS.oxfordBurgundy2,
        PHOTOS.oxfordBlack3,
        PHOTOS.oxfordBlack4,
        PHOTOS.oxfordBurgundy1,
        PHOTOS.oxfordBurgundy2,
      ],
    }),
    colors: [COLORS.black, COLORS.burgundy],
    sizes: SHOE_SIZE_OPTIONS,
    variants: makeVariants(SIZES_SHOE, [COLORS.black, COLORS.burgundy]),
    material: "Full-grain calfskin, leather sole",
    care: "Use shoe trees. Polish with neutral cream.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["shoes"],
  },
  {
    id: "5",
    slug: "belgravia-loafer",
    name: "Belgravia Penny Loafer",
    description: "Unlined penny loafer in full-grain leather with hand-stitched apron.",
    gender: "men",
    category: "shoes",
    subcategory: "loafer",
    price: 750,
    currency: "USD",
    images: gallery(
      PHOTOS.loafer1,
      PHOTOS.loafer2,
      PHOTOS.loafer3,
      PHOTOS.loafer2,
      PHOTOS.loafer1,
      PHOTOS.loafer3
    ),
    colorImages: colorGalleries({
      burgundy: [
        PHOTOS.loafer1,
        PHOTOS.loafer2,
        PHOTOS.loafer3,
        PHOTOS.loafer2,
        PHOTOS.loafer1,
        PHOTOS.loafer3,
      ],
      black: [
        PHOTOS.loafer2,
        PHOTOS.loafer3,
        PHOTOS.loafer1,
        PHOTOS.loafer3,
        PHOTOS.loafer2,
        PHOTOS.loafer1,
      ],
    }),
    colors: [COLORS.burgundy, COLORS.black],
    sizes: SHOE_SIZE_OPTIONS,
    variants: makeVariants(SIZES_SHOE, [COLORS.burgundy, COLORS.black]),
    material: "Full-grain leather, rubber inset heel",
    care: "Brush and condition monthly.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["shoes"],
  },
  {
    id: "6",
    slug: "albany-weekender",
    name: "Albany Weekender",
    description: "Bridle leather weekender with solid brass hardware and cotton twill lining.",
    gender: "men",
    category: "bags",
    subcategory: "weekender",
    price: 1850,
    currency: "USD",
    images: gallery(
      PHOTOS.bagWeekender1,
      PHOTOS.bagWeekender2,
      PHOTOS.bagWeekender3,
      PHOTOS.bagWeekender2,
      PHOTOS.bagWeekender3,
      PHOTOS.bagWeekender1
    ),
    colorImages: colorGalleries({
      navy: [
        PHOTOS.bagWeekender1,
        PHOTOS.bagWeekender2,
        PHOTOS.bagWeekender3,
        PHOTOS.bagWeekender2,
        PHOTOS.bagWeekender3,
        PHOTOS.bagWeekender1,
      ],
      cream: [
        PHOTOS.bagWeekender2,
        PHOTOS.bagWeekender3,
        PHOTOS.bagWeekender1,
        PHOTOS.bagWeekender3,
        PHOTOS.bagWeekender1,
        PHOTOS.bagWeekender2,
      ],
    }),
    colors: [COLORS.navy, COLORS.cream],
    sizes: [{ id: "os", label: "One Size", value: "OS", inStock: true }],
    variants: makeVariants(["OS"], [COLORS.navy, COLORS.cream]),
    material: "Bridle leather, brass hardware",
    care: "Condition leather seasonally.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["bags"],
  },
  {
    id: "7",
    slug: "piccadilly-clutch",
    name: "Piccadilly Evening Clutch",
    description: "Satin evening clutch with detachable chain and silk interior.",
    gender: "women",
    category: "bags",
    subcategory: "clutch",
    price: 620,
    currency: "USD",
    images: gallery(
      PHOTOS.clutch1,
      PHOTOS.clutch2,
      PHOTOS.clutch3,
      PHOTOS.bagWeekender1,
      PHOTOS.bagWeekender2,
      PHOTOS.bagWeekender3
    ),
    colorImages: colorGalleries({
      black: [
        PHOTOS.clutch1,
        PHOTOS.clutch2,
        PHOTOS.clutch3,
        PHOTOS.bagWeekender1,
        PHOTOS.bagWeekender2,
        PHOTOS.bagWeekender3,
      ],
      gold: [
        PHOTOS.clutch2,
        PHOTOS.clutch3,
        PHOTOS.clutch1,
        PHOTOS.bagWeekender2,
        PHOTOS.bagWeekender3,
        PHOTOS.bagWeekender1,
      ],
    }),
    colors: [COLORS.black, COLORS.gold],
    sizes: [{ id: "os", label: "One Size", value: "OS", inStock: true }],
    variants: makeVariants(["OS"], [COLORS.black, COLORS.gold]),
    material: "Satin exterior, silk lining",
    care: "Store in dust bag. Spot clean only.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["bags", "evening"],
  },
  {
    id: "8",
    slug: "no-14-bespoke",
    name: "No. 14 Bespoke Eau de Parfum",
    description: "Oud, iris, and suede. 50ml extrait composed in Grasse.",
    gender: "women",
    category: "perfumes",
    subcategory: "eau-de-parfum",
    price: 320,
    currency: "USD",
    images: gallery(
      PHOTOS.perfume1,
      PHOTOS.perfume2,
      PHOTOS.perfume3,
      PHOTOS.cologne1,
      PHOTOS.cologne2,
      PHOTOS.perfume1
    ),
    colorImages: colorGalleries({
      clear: [
        PHOTOS.perfume1,
        PHOTOS.perfume2,
        PHOTOS.perfume3,
        PHOTOS.cologne1,
        PHOTOS.cologne2,
        PHOTOS.perfume1,
      ],
    }),
    colors: [{ id: "clear", label: "Clear", value: "clear", inStock: true }],
    sizes: [
      { id: "50", label: "50 ml", value: "50", inStock: true },
      { id: "100", label: "100 ml", value: "100", inStock: true },
    ],
    variants: [
      { id: "50-clear", sku: "SR-PERF-50", size: "50", color: "clear", volumeMl: 50, priceModifier: 0, inStock: true },
      { id: "100-clear", sku: "SR-PERF-100", size: "100", color: "clear", volumeMl: 100, priceModifier: 120, inStock: true },
    ],
    material: "Extrait concentration, glass flacon",
    care: "Store away from direct sunlight.",
    shippingNote: "Ships via certified fragrance courier.",
    tags: ["fragrance"],
  },
  {
    id: "9",
    slug: "savile-cologne",
    name: "Savile Cologne",
    description: "Bergamot, vetiver, and white musk. Unisex cologne.",
    gender: "men",
    category: "perfumes",
    subcategory: "cologne",
    price: 185,
    currency: "USD",
    images: gallery(
      PHOTOS.cologne1,
      PHOTOS.cologne2,
      PHOTOS.perfume2,
      PHOTOS.perfume3,
      PHOTOS.perfume1,
      PHOTOS.cologne1
    ),
    colorImages: colorGalleries({
      clear: [
        PHOTOS.cologne1,
        PHOTOS.cologne2,
        PHOTOS.perfume2,
        PHOTOS.perfume3,
        PHOTOS.perfume1,
        PHOTOS.cologne1,
      ],
    }),
    colors: [{ id: "clear", label: "Clear", value: "clear", inStock: true }],
    sizes: [{ id: "100", label: "100 ml", value: "100", inStock: true }],
    variants: [{ id: "100-clear", sku: "SR-COL-100", size: "100", volumeMl: 100, priceModifier: 0, inStock: true }],
    material: "Eau de cologne, recyclable glass",
    care: "Keep cap secured between uses.",
    shippingNote: "Ships via certified fragrance courier.",
    tags: ["fragrance"],
  },
  {
    id: "10",
    slug: "gold-enamel-cufflinks",
    name: "Gold Enamel Cufflinks",
    description: "18k gold-plated cufflinks with navy enamel inlay.",
    gender: "men",
    category: "accessories",
    subcategory: "cufflinks",
    price: 420,
    currency: "USD",
    images: gallery(
      PHOTOS.cufflinks1,
      PHOTOS.cufflinks2,
      PHOTOS.cufflinks3,
      PHOTOS.accessoriesPromo,
      PHOTOS.belt1,
      PHOTOS.belt2
    ),
    colorImages: colorGalleries({
      navy: [
        PHOTOS.cufflinks1,
        PHOTOS.cufflinks2,
        PHOTOS.cufflinks3,
        PHOTOS.accessoriesPromo,
        PHOTOS.belt1,
        PHOTOS.belt2,
      ],
      gold: [
        PHOTOS.cufflinks2,
        PHOTOS.cufflinks3,
        PHOTOS.cufflinks1,
        PHOTOS.accessoriesPromo,
        PHOTOS.belt2,
        PHOTOS.belt3,
      ],
    }),
    colors: [COLORS.navy, COLORS.gold],
    sizes: [{ id: "os", label: "One Size", value: "OS", inStock: true }],
    variants: makeVariants(["OS"], [COLORS.navy, COLORS.gold]),
    material: "Gold-plated brass, enamel inlay",
    care: "Polish with a soft cloth. Avoid water.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["accessories", "cufflinks"],
  },
  {
    id: "11",
    slug: "reversible-silk-belt",
    name: "Reversible Silk Belt",
    description: "Reversible silk and leather belt with brushed gold buckle.",
    gender: "men",
    category: "accessories",
    subcategory: "belts",
    price: 295,
    currency: "USD",
    images: gallery(
      PHOTOS.belt1,
      PHOTOS.belt2,
      PHOTOS.belt3,
      PHOTOS.cufflinks1,
      PHOTOS.cufflinks2,
      PHOTOS.cufflinks3
    ),
    colorImages: colorGalleries({
      navy: [
        PHOTOS.belt1,
        PHOTOS.belt2,
        PHOTOS.belt3,
        PHOTOS.cufflinks1,
        PHOTOS.cufflinks2,
        PHOTOS.cufflinks3,
      ],
      black: [
        PHOTOS.belt2,
        PHOTOS.belt3,
        PHOTOS.belt1,
        PHOTOS.cufflinks2,
        PHOTOS.cufflinks3,
        PHOTOS.cufflinks1,
      ],
    }),
    colors: [COLORS.navy, COLORS.black],
    sizes: ["80", "85", "90", "95", "100"].map((s) => ({ id: s, label: `${s} cm`, value: s, inStock: true })),
    variants: makeVariants(["80", "85", "90", "95", "100"], [COLORS.navy, COLORS.black]),
    material: "Silk and leather, gold-plated buckle",
    care: "Rotate sides seasonally. Store flat.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["accessories", "belts"],
  },
  {
    id: "12",
    slug: "kensington-blazer-w",
    name: "Kensington Tailored Blazer",
    description: "Single-breasted blazer in Italian stretch wool with hand-finished buttonholes.",
    gender: "women",
    category: "suits",
    subcategory: "blazer",
    price: 2100,
    currency: "USD",
    images: gallery(
      PHOTOS.blazerW1,
      PHOTOS.blazerW2,
      PHOTOS.blazerW3,
      PHOTOS.suitNavy1,
      PHOTOS.suitNavy2,
      PHOTOS.suitNavy3
    ),
    colorImages: colorGalleries({
      navy: [
        PHOTOS.blazerW1,
        PHOTOS.blazerW2,
        PHOTOS.blazerW3,
        PHOTOS.suitNavy1,
        PHOTOS.suitNavy2,
        PHOTOS.suitNavy3,
      ],
      cream: [
        PHOTOS.blazerW2,
        PHOTOS.blazerW3,
        PHOTOS.blazerW1,
        PHOTOS.suitNavy2,
        PHOTOS.suitNavy3,
        PHOTOS.suitNavy4,
      ],
    }),
    colors: [COLORS.navy, COLORS.cream],
    sizes: ["34", "36", "38", "40", "42"].map((s) => ({ id: s, label: s, value: s, inStock: true })),
    variants: makeVariants(["34", "36", "38", "40", "42"], [COLORS.navy, COLORS.cream]),
    material: "Italian stretch wool, silk lining",
    care: "Dry clean only.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["women", "new"],
    isNew: true,
    isBespokeEligible: true,
  },
  {
    id: "13",
    slug: "bond-st-pump",
    name: "Bond Street Satin Pump",
    description: "85mm satin pump with leather sole and cushioned insole.",
    gender: "women",
    category: "shoes",
    subcategory: "pump",
    price: 680,
    currency: "USD",
    images: gallery(
      PHOTOS.pump1,
      PHOTOS.pump2,
      PHOTOS.oxfordBlack1,
      PHOTOS.oxfordBlack2,
      PHOTOS.loafer1,
      PHOTOS.loafer2
    ),
    colorImages: colorGalleries({
      black: [
        PHOTOS.pump1,
        PHOTOS.pump2,
        PHOTOS.oxfordBlack1,
        PHOTOS.oxfordBlack2,
        PHOTOS.loafer1,
        PHOTOS.loafer2,
      ],
      burgundy: [
        PHOTOS.pump2,
        PHOTOS.pump1,
        PHOTOS.oxfordBurgundy1,
        PHOTOS.oxfordBurgundy2,
        PHOTOS.loafer1,
        PHOTOS.loafer2,
      ],
    }),
    colors: [COLORS.black, COLORS.burgundy],
    sizes: ["36", "37", "38", "39", "40"].map((s) => ({ id: s, label: s, value: s, inStock: true })),
    variants: makeVariants(["36", "37", "38", "39", "40"], [COLORS.black, COLORS.burgundy]),
    material: "Satin upper, leather sole",
    care: "Protect soles before first wear.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["shoes", "evening"],
  },
  {
    id: "14",
    slug: "junior-eton-blazer",
    name: "Junior Eton Blazer",
    description: "Half-lined wool blazer for young gentlemen. School and occasion ready.",
    gender: "kids",
    category: "suits",
    subcategory: "blazer",
    price: 480,
    currency: "USD",
    images: gallery(
      PHOTOS.kidsBlazer1,
      PHOTOS.kidsBlazer2,
      PHOTOS.kidsPromo,
      PHOTOS.suitNavy1,
      PHOTOS.suitNavy2,
      PHOTOS.suitNavy3
    ),
    colorImages: colorGalleries({
      navy: [
        PHOTOS.kidsBlazer1,
        PHOTOS.kidsBlazer2,
        PHOTOS.kidsPromo,
        PHOTOS.suitNavy1,
        PHOTOS.suitNavy2,
        PHOTOS.suitNavy3,
      ],
    }),
    colors: [COLORS.navy],
    sizes: ["6", "8", "10", "12", "14"].map((s) => ({ id: s, label: `Age ${s}`, value: s, inStock: true })),
    variants: makeVariants(["6", "8", "10", "12", "14"], [COLORS.navy]),
    material: "Wool blend, half canvas",
    care: "Dry clean only.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["kids"],
  },
  {
    id: "15",
    slug: "little-piccadilly-loafer",
    name: "Little Piccadilly Loafer",
    description: "Children's leather loafer with flexible rubber sole.",
    gender: "kids",
    category: "shoes",
    subcategory: "loafer",
    price: 195,
    currency: "USD",
    images: gallery(
      PHOTOS.loafer1,
      PHOTOS.loafer2,
      PHOTOS.loafer3,
      PHOTOS.oxfordBlack1,
      PHOTOS.oxfordBlack2,
      PHOTOS.oxfordBurgundy1
    ),
    colorImages: colorGalleries({
      black: [
        PHOTOS.loafer1,
        PHOTOS.loafer2,
        PHOTOS.loafer3,
        PHOTOS.oxfordBlack1,
        PHOTOS.oxfordBlack2,
        PHOTOS.oxfordBlack3,
      ],
      burgundy: [
        PHOTOS.loafer2,
        PHOTOS.loafer1,
        PHOTOS.loafer3,
        PHOTOS.oxfordBurgundy1,
        PHOTOS.oxfordBurgundy2,
        PHOTOS.oxfordBlack4,
      ],
    }),
    colors: [COLORS.black, COLORS.burgundy],
    sizes: ["28", "30", "32", "34"].map((s) => ({ id: s, label: `EU ${s}`, value: s, inStock: true })),
    variants: makeVariants(["28", "30", "32", "34"], [COLORS.black, COLORS.burgundy]),
    material: "Leather upper, rubber sole",
    care: "Wipe clean with damp cloth.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["kids", "shoes"],
  },
  {
    id: "16",
    slug: "rose-velvet-bow",
    name: "Rose Velvet Bow Belt",
    description: "Velvet bow belt with antique gold clasp.",
    gender: "women",
    category: "accessories",
    subcategory: "belts",
    price: 245,
    currency: "USD",
    images: gallery(
      PHOTOS.belt2,
      PHOTOS.belt3,
      PHOTOS.belt1,
      PHOTOS.belt2,
      PHOTOS.belt3,
      PHOTOS.belt1
    ),
    colorImages: colorGalleries({
      burgundy: [
        PHOTOS.belt2,
        PHOTOS.belt3,
        PHOTOS.belt1,
        PHOTOS.belt2,
        PHOTOS.belt3,
        PHOTOS.belt1,
      ],
      black: [
        PHOTOS.belt3,
        PHOTOS.belt2,
        PHOTOS.belt1,
        PHOTOS.belt3,
        PHOTOS.belt2,
        PHOTOS.belt1,
      ],
    }),
    colors: [COLORS.burgundy, COLORS.black],
    sizes: SIZES_STD.map((s) => ({ id: s, label: s, value: s, inStock: true })),
    variants: makeVariants(SIZES_STD, [COLORS.burgundy, COLORS.black]),
    material: "Velvet, antique gold clasp",
    care: "Store rolled, not folded.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["accessories", "belts"],
  },
  {
    id: "17",
    slug: "mayfair-card-wallet",
    name: "Mayfair Card Wallet",
    description: "Slim card wallet in grained calfskin with six slots and central pocket.",
    gender: "men",
    category: "accessories",
    subcategory: "wallets",
    price: 385,
    currency: "USD",
    images: gallery(
      PHOTOS.wallet1,
      PHOTOS.wallet2,
      PHOTOS.wallet3,
      PHOTOS.wallet2,
      PHOTOS.wallet3,
      PHOTOS.wallet1
    ),
    colorImages: colorGalleries({
      black: [
        PHOTOS.wallet1,
        PHOTOS.wallet2,
        PHOTOS.wallet3,
        PHOTOS.wallet2,
        PHOTOS.wallet3,
        PHOTOS.wallet1,
      ],
      navy: [
        PHOTOS.wallet2,
        PHOTOS.wallet3,
        PHOTOS.wallet1,
        PHOTOS.wallet3,
        PHOTOS.wallet1,
        PHOTOS.wallet2,
      ],
    }),
    colors: [COLORS.black, COLORS.navy],
    sizes: [{ id: "os", label: "One Size", value: "OS", inStock: true }],
    variants: makeVariants(["OS"], [COLORS.black, COLORS.navy]),
    material: "Grained calfskin",
    care: "Condition twice yearly.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["accessories", "wallets"],
  },
  {
    id: "18",
    slug: "kensington-continental-wallet",
    name: "Kensington Continental Wallet",
    description: "Zip-around continental wallet with gusseted coin pouch.",
    gender: "women",
    category: "accessories",
    subcategory: "wallets",
    price: 520,
    currency: "USD",
    images: gallery(
      PHOTOS.wallet3,
      PHOTOS.wallet2,
      PHOTOS.wallet1,
      PHOTOS.wallet2,
      PHOTOS.wallet3,
      PHOTOS.wallet1
    ),
    colorImages: colorGalleries({
      black: [
        PHOTOS.wallet3,
        PHOTOS.wallet2,
        PHOTOS.wallet1,
        PHOTOS.wallet2,
        PHOTOS.wallet3,
        PHOTOS.wallet1,
      ],
      gold: [
        PHOTOS.wallet2,
        PHOTOS.wallet1,
        PHOTOS.wallet3,
        PHOTOS.wallet1,
        PHOTOS.wallet2,
        PHOTOS.wallet3,
      ],
    }),
    colors: [COLORS.black, COLORS.gold],
    sizes: [{ id: "os", label: "One Size", value: "OS", inStock: true }],
    variants: makeVariants(["OS"], [COLORS.black, COLORS.gold]),
    material: "Lambskin leather, gold hardware",
    care: "Store in dust bag.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["accessories", "wallets"],
  },
  // ─── Additional Suits ─────────────────────────────────
  {
    id: "19",
    slug: "westminster-three-piece",
    name: "Westminster Three-Piece Suit",
    description: "Classic three-piece in worsted wool with notch lapel, working buttonholes, and matching waistcoat.",
    gender: "men",
    category: "suits",
    subcategory: "three-piece",
    price: 4800,
    currency: "USD",
    images: gallery(
      PHOTOS.suitNavy3,
      PHOTOS.suitNavy4,
      PHOTOS.suitNavy5,
      PHOTOS.suitNavy6,
      PHOTOS.suitNavy1,
      PHOTOS.suitNavy2
    ),
    colorImages: colorGalleries({
      charcoal: [PHOTOS.suitNavy3, PHOTOS.suitNavy4, PHOTOS.suitNavy5, PHOTOS.suitNavy6, PHOTOS.suitNavy1, PHOTOS.suitNavy2],
      navy: [PHOTOS.suitNavy1, PHOTOS.suitNavy2, PHOTOS.suitNavy3, PHOTOS.suitNavy4, PHOTOS.suitNavy5, PHOTOS.suitNavy6],
    }),
    colors: [COLORS.charcoal, COLORS.navy],
    sizes: SIZES_SUIT.map((s) => ({ id: s, label: s, value: s, inStock: true })),
    variants: makeVariants(SIZES_SUIT, [COLORS.charcoal, COLORS.navy]),
    material: "Worsted wool, Bemberg lining",
    care: "Dry clean only.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["suits", "new"],
    isNew: true,
    isBespokeEligible: true,
  },
  {
    id: "20",
    slug: "buckingham-dinner-suit",
    name: "Buckingham Shawl-Collar Dinner Suit",
    description: "Single-button shawl collar dinner suit in midnight wool with grosgrain facings.",
    gender: "men",
    category: "suits",
    subcategory: "tuxedo",
    price: 4400,
    currency: "USD",
    images: gallery(
      PHOTOS.tuxedo2,
      PHOTOS.tuxedo3,
      PHOTOS.tuxedo4,
      PHOTOS.tuxedo1,
      PHOTOS.morningCoat1,
      PHOTOS.morningCoat2
    ),
    colorImages: colorGalleries({
      black: [PHOTOS.tuxedo2, PHOTOS.tuxedo3, PHOTOS.tuxedo4, PHOTOS.tuxedo1, PHOTOS.morningCoat1, PHOTOS.morningCoat2],
    }),
    colors: [COLORS.black],
    sizes: SIZES_SUIT.map((s) => ({ id: s, label: s, value: s, inStock: true })),
    variants: makeVariants(SIZES_SUIT, [COLORS.black]),
    material: "Wool, grosgrain facings",
    care: "Dry clean only.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["evening"],
    isBespokeEligible: true,
  },
  {
    id: "21",
    slug: "regent-wool-blazer",
    name: "Regent Single-Breasted Blazer",
    description: "Lightweight unstructured blazer in hopsack wool with patch pockets.",
    gender: "men",
    category: "suits",
    subcategory: "blazer",
    price: 2600,
    currency: "USD",
    images: gallery(
      PHOTOS.suitNavy2,
      PHOTOS.suitNavy3,
      PHOTOS.suitNavy1,
      PHOTOS.suitNavy4,
      PHOTOS.suitNavy5,
      PHOTOS.suitNavy6
    ),
    colorImages: colorGalleries({
      navy: [PHOTOS.suitNavy2, PHOTOS.suitNavy3, PHOTOS.suitNavy1, PHOTOS.suitNavy4, PHOTOS.suitNavy5, PHOTOS.suitNavy6],
      cream: [PHOTOS.suitNavy5, PHOTOS.suitNavy6, PHOTOS.suitNavy4, PHOTOS.suitNavy1, PHOTOS.suitNavy2, PHOTOS.suitNavy3],
    }),
    colors: [COLORS.navy, COLORS.cream],
    sizes: SIZES_SUIT.map((s) => ({ id: s, label: s, value: s, inStock: true })),
    variants: makeVariants(SIZES_SUIT, [COLORS.navy, COLORS.cream]),
    material: "Hopsack wool, half canvas",
    care: "Dry clean only.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["suits"],
  },
  {
    id: "22",
    slug: "belgrave-two-piece-w",
    name: "Belgrave Tailored Two-Piece",
    description: "Women's two-piece in fluid Italian wool with cinched waist and tapered trouser.",
    gender: "women",
    category: "suits",
    subcategory: "two-piece",
    price: 3200,
    currency: "USD",
    images: gallery(
      PHOTOS.blazerW2,
      PHOTOS.blazerW3,
      PHOTOS.blazerW1,
      PHOTOS.suitNavy1,
      PHOTOS.suitNavy2,
      PHOTOS.suitNavy3
    ),
    colorImages: colorGalleries({
      charcoal: [PHOTOS.blazerW2, PHOTOS.blazerW3, PHOTOS.blazerW1, PHOTOS.suitNavy1, PHOTOS.suitNavy2, PHOTOS.suitNavy3],
      cream: [PHOTOS.blazerW3, PHOTOS.blazerW2, PHOTOS.blazerW1, PHOTOS.suitNavy3, PHOTOS.suitNavy2, PHOTOS.suitNavy1],
    }),
    colors: [COLORS.charcoal, COLORS.cream],
    sizes: ["34", "36", "38", "40", "42"].map((s) => ({ id: s, label: s, value: s, inStock: true })),
    variants: makeVariants(["34", "36", "38", "40", "42"], [COLORS.charcoal, COLORS.cream]),
    material: "Italian wool, silk lining",
    care: "Dry clean only.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["women", "new"],
    isNew: true,
    isBespokeEligible: true,
  },
  {
    id: "23",
    slug: "eton-junior-tuxedo",
    name: "Eton Junior Tuxedo",
    description: "Children's two-piece dinner suit with satin lapels for school galas and weddings.",
    gender: "kids",
    category: "suits",
    subcategory: "tuxedo",
    price: 620,
    currency: "USD",
    images: gallery(
      PHOTOS.kidsBlazer2,
      PHOTOS.kidsBlazer1,
      PHOTOS.kidsPromo,
      PHOTOS.tuxedo1,
      PHOTOS.tuxedo2,
      PHOTOS.tuxedo3
    ),
    colorImages: colorGalleries({
      black: [PHOTOS.kidsBlazer2, PHOTOS.kidsBlazer1, PHOTOS.kidsPromo, PHOTOS.tuxedo1, PHOTOS.tuxedo2, PHOTOS.tuxedo3],
    }),
    colors: [COLORS.black],
    sizes: ["6", "8", "10", "12", "14"].map((s) => ({ id: s, label: `Age ${s}`, value: s, inStock: true })),
    variants: makeVariants(["6", "8", "10", "12", "14"], [COLORS.black]),
    material: "Wool blend, satin lapel facings",
    care: "Dry clean only.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["kids", "evening"],
  },
  // ─── Additional Shoes ─────────────────────────────────
  {
    id: "24",
    slug: "knightsbridge-chelsea-boot",
    name: "Knightsbridge Chelsea Boot",
    description: "Calfskin Chelsea boot with elasticated side gussets and Goodyear-welted leather sole.",
    gender: "men",
    category: "shoes",
    subcategory: "chelsea-boot",
    price: 980,
    currency: "USD",
    images: gallery(
      PHOTOS.oxfordBlack2,
      PHOTOS.oxfordBlack3,
      PHOTOS.oxfordBlack4,
      PHOTOS.oxfordBlack1,
      PHOTOS.oxfordBlack3,
      PHOTOS.oxfordBlack2
    ),
    colorImages: colorGalleries({
      black: [PHOTOS.oxfordBlack2, PHOTOS.oxfordBlack3, PHOTOS.oxfordBlack4, PHOTOS.oxfordBlack1, PHOTOS.oxfordBlack3, PHOTOS.oxfordBlack2],
      burgundy: [PHOTOS.oxfordBurgundy1, PHOTOS.oxfordBurgundy2, PHOTOS.oxfordBlack3, PHOTOS.oxfordBlack4, PHOTOS.oxfordBurgundy1, PHOTOS.oxfordBurgundy2],
    }),
    colors: [COLORS.black, COLORS.burgundy],
    sizes: SHOE_SIZE_OPTIONS,
    variants: makeVariants(SIZES_SHOE, [COLORS.black, COLORS.burgundy]),
    material: "Calfskin upper, leather sole",
    care: "Use shoe trees. Polish with neutral cream.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["shoes", "new"],
    isNew: true,
  },
  {
    id: "25",
    slug: "mayfair-velvet-loafer",
    name: "Mayfair Velvet Slipper",
    description: "Hand-embroidered velvet evening slipper with leather sole and silk lining.",
    gender: "men",
    category: "shoes",
    subcategory: "loafer",
    price: 720,
    currency: "USD",
    images: gallery(
      PHOTOS.loafer3,
      PHOTOS.loafer2,
      PHOTOS.loafer1,
      PHOTOS.loafer2,
      PHOTOS.loafer3,
      PHOTOS.loafer1
    ),
    colorImages: colorGalleries({
      burgundy: [PHOTOS.loafer3, PHOTOS.loafer2, PHOTOS.loafer1, PHOTOS.loafer2, PHOTOS.loafer3, PHOTOS.loafer1],
      black: [PHOTOS.loafer2, PHOTOS.loafer1, PHOTOS.loafer3, PHOTOS.loafer1, PHOTOS.loafer2, PHOTOS.loafer3],
    }),
    colors: [COLORS.burgundy, COLORS.black],
    sizes: SHOE_SIZE_OPTIONS,
    variants: makeVariants(SIZES_SHOE, [COLORS.burgundy, COLORS.black]),
    material: "Velvet upper, leather sole",
    care: "Brush nap regularly. Avoid moisture.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["shoes", "evening"],
  },
  {
    id: "26",
    slug: "battersea-court-sandal",
    name: "Battersea Strappy Sandal",
    description: "75mm strappy sandal with adjustable ankle buckle and leather sole.",
    gender: "women",
    category: "shoes",
    subcategory: "sandal",
    price: 640,
    currency: "USD",
    images: gallery(
      PHOTOS.pump2,
      PHOTOS.pump1,
      PHOTOS.pump2,
      PHOTOS.pump1,
      PHOTOS.pump2,
      PHOTOS.pump1
    ),
    colorImages: colorGalleries({
      gold: [PHOTOS.pump2, PHOTOS.pump1, PHOTOS.pump2, PHOTOS.pump1, PHOTOS.pump2, PHOTOS.pump1],
      black: [PHOTOS.pump1, PHOTOS.pump2, PHOTOS.pump1, PHOTOS.pump2, PHOTOS.pump1, PHOTOS.pump2],
    }),
    colors: [COLORS.gold, COLORS.black],
    sizes: ["36", "37", "38", "39", "40"].map((s) => ({ id: s, label: s, value: s, inStock: true })),
    variants: makeVariants(["36", "37", "38", "39", "40"], [COLORS.gold, COLORS.black]),
    material: "Calf leather, leather sole",
    care: "Wipe with damp cloth. Store in dust bag.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["shoes", "new"],
    isNew: true,
  },
  {
    id: "27",
    slug: "soho-leather-sneaker",
    name: "Soho Low-Top Sneaker",
    description: "Italian-made low-top sneaker in supple calfskin with cushioned cup sole.",
    gender: "men",
    category: "shoes",
    subcategory: "sneaker",
    price: 590,
    currency: "USD",
    images: gallery(
      PHOTOS.loafer2,
      PHOTOS.loafer3,
      PHOTOS.loafer1,
      PHOTOS.loafer3,
      PHOTOS.loafer2,
      PHOTOS.loafer1
    ),
    colorImages: colorGalleries({
      cream: [PHOTOS.loafer2, PHOTOS.loafer3, PHOTOS.loafer1, PHOTOS.loafer3, PHOTOS.loafer2, PHOTOS.loafer1],
      black: [PHOTOS.loafer1, PHOTOS.loafer2, PHOTOS.loafer3, PHOTOS.loafer2, PHOTOS.loafer1, PHOTOS.loafer3],
    }),
    colors: [COLORS.cream, COLORS.black],
    sizes: SHOE_SIZE_OPTIONS,
    variants: makeVariants(SIZES_SHOE, [COLORS.cream, COLORS.black]),
    material: "Calfskin, rubber cup sole",
    care: "Wipe clean. Use protector spray.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["shoes"],
  },
  {
    id: "28",
    slug: "brompton-riding-boot",
    name: "Brompton Tall Riding Boot",
    description: "Knee-high leather riding boot with side zip and stacked-leather heel.",
    gender: "women",
    category: "shoes",
    subcategory: "boot",
    price: 1180,
    currency: "USD",
    images: gallery(
      PHOTOS.oxfordBlack4,
      PHOTOS.oxfordBlack3,
      PHOTOS.oxfordBlack2,
      PHOTOS.oxfordBlack1,
      PHOTOS.pump1,
      PHOTOS.pump2
    ),
    colorImages: colorGalleries({
      black: [PHOTOS.oxfordBlack4, PHOTOS.oxfordBlack3, PHOTOS.oxfordBlack2, PHOTOS.oxfordBlack1, PHOTOS.pump1, PHOTOS.pump2],
      burgundy: [PHOTOS.oxfordBurgundy1, PHOTOS.oxfordBurgundy2, PHOTOS.oxfordBlack3, PHOTOS.oxfordBlack4, PHOTOS.pump2, PHOTOS.pump1],
    }),
    colors: [COLORS.black, COLORS.burgundy],
    sizes: ["36", "37", "38", "39", "40"].map((s) => ({ id: s, label: s, value: s, inStock: true })),
    variants: makeVariants(["36", "37", "38", "39", "40"], [COLORS.black, COLORS.burgundy]),
    material: "Full-grain leather, stacked heel",
    care: "Condition every six months.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["shoes"],
  },
  // ─── Additional Bags ──────────────────────────────────
  {
    id: "29",
    slug: "hampstead-tote",
    name: "Hampstead Structured Tote",
    description: "Structured day tote in grained leather with detachable pouch and brass feet.",
    gender: "women",
    category: "bags",
    subcategory: "tote",
    price: 1450,
    currency: "USD",
    images: gallery(
      PHOTOS.bagWeekender2,
      PHOTOS.bagWeekender3,
      PHOTOS.bagWeekender1,
      PHOTOS.clutch2,
      PHOTOS.clutch3,
      PHOTOS.clutch1
    ),
    colorImages: colorGalleries({
      black: [PHOTOS.bagWeekender2, PHOTOS.bagWeekender3, PHOTOS.bagWeekender1, PHOTOS.clutch2, PHOTOS.clutch3, PHOTOS.clutch1],
      cream: [PHOTOS.bagWeekender3, PHOTOS.bagWeekender2, PHOTOS.bagWeekender1, PHOTOS.clutch3, PHOTOS.clutch2, PHOTOS.clutch1],
    }),
    colors: [COLORS.black, COLORS.cream],
    sizes: [{ id: "os", label: "One Size", value: "OS", inStock: true }],
    variants: makeVariants(["OS"], [COLORS.black, COLORS.cream]),
    material: "Grained calf leather, brass hardware",
    care: "Condition leather seasonally.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["bags", "new"],
    isNew: true,
  },
  {
    id: "30",
    slug: "holland-park-briefcase",
    name: "Holland Park Briefcase",
    description: "Slim attaché briefcase in bridle leather with combination lock and pen loops.",
    gender: "men",
    category: "bags",
    subcategory: "briefcase",
    price: 2200,
    currency: "USD",
    images: gallery(
      PHOTOS.bagWeekender3,
      PHOTOS.bagWeekender1,
      PHOTOS.bagWeekender2,
      PHOTOS.bagWeekender3,
      PHOTOS.bagWeekender1,
      PHOTOS.bagWeekender2
    ),
    colorImages: colorGalleries({
      black: [PHOTOS.bagWeekender3, PHOTOS.bagWeekender1, PHOTOS.bagWeekender2, PHOTOS.bagWeekender3, PHOTOS.bagWeekender1, PHOTOS.bagWeekender2],
      burgundy: [PHOTOS.bagWeekender1, PHOTOS.bagWeekender2, PHOTOS.bagWeekender3, PHOTOS.bagWeekender2, PHOTOS.bagWeekender3, PHOTOS.bagWeekender1],
    }),
    colors: [COLORS.black, COLORS.burgundy],
    sizes: [{ id: "os", label: "One Size", value: "OS", inStock: true }],
    variants: makeVariants(["OS"], [COLORS.black, COLORS.burgundy]),
    material: "Bridle leather, brass combination lock",
    care: "Wipe clean. Condition twice yearly.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["bags"],
  },
  {
    id: "31",
    slug: "marylebone-crossbody",
    name: "Marylebone Crossbody",
    description: "Compact crossbody in lambskin with woven leather strap and magnetic closure.",
    gender: "women",
    category: "bags",
    subcategory: "crossbody",
    price: 980,
    currency: "USD",
    images: gallery(
      PHOTOS.clutch2,
      PHOTOS.clutch1,
      PHOTOS.clutch3,
      PHOTOS.bagWeekender2,
      PHOTOS.bagWeekender3,
      PHOTOS.bagWeekender1
    ),
    colorImages: colorGalleries({
      burgundy: [PHOTOS.clutch2, PHOTOS.clutch1, PHOTOS.clutch3, PHOTOS.bagWeekender2, PHOTOS.bagWeekender3, PHOTOS.bagWeekender1],
      black: [PHOTOS.clutch1, PHOTOS.clutch2, PHOTOS.clutch3, PHOTOS.bagWeekender3, PHOTOS.bagWeekender2, PHOTOS.bagWeekender1],
    }),
    colors: [COLORS.burgundy, COLORS.black],
    sizes: [{ id: "os", label: "One Size", value: "OS", inStock: true }],
    variants: makeVariants(["OS"], [COLORS.burgundy, COLORS.black]),
    material: "Lambskin, gold hardware",
    care: "Store in dust bag. Avoid prolonged sunlight.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["bags"],
  },
  {
    id: "32",
    slug: "soho-backpack",
    name: "Soho City Backpack",
    description: "Streamlined city backpack in coated canvas with leather trim and padded laptop sleeve.",
    gender: "men",
    category: "bags",
    subcategory: "backpack",
    price: 1320,
    currency: "USD",
    images: gallery(
      PHOTOS.bagWeekender1,
      PHOTOS.bagWeekender3,
      PHOTOS.bagWeekender2,
      PHOTOS.bagWeekender1,
      PHOTOS.bagWeekender3,
      PHOTOS.bagWeekender2
    ),
    colorImages: colorGalleries({
      black: [PHOTOS.bagWeekender1, PHOTOS.bagWeekender3, PHOTOS.bagWeekender2, PHOTOS.bagWeekender1, PHOTOS.bagWeekender3, PHOTOS.bagWeekender2],
      navy: [PHOTOS.bagWeekender2, PHOTOS.bagWeekender1, PHOTOS.bagWeekender3, PHOTOS.bagWeekender2, PHOTOS.bagWeekender1, PHOTOS.bagWeekender3],
    }),
    colors: [COLORS.black, COLORS.navy],
    sizes: [{ id: "os", label: "One Size", value: "OS", inStock: true }],
    variants: makeVariants(["OS"], [COLORS.black, COLORS.navy]),
    material: "Coated canvas, leather trim",
    care: "Wipe clean. Use leather conditioner on trims.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["bags"],
  },
  {
    id: "33",
    slug: "chelsea-mini-bag",
    name: "Chelsea Top-Handle Mini",
    description: "Petite top-handle bag with quilted leather body and short chain shoulder strap.",
    gender: "women",
    category: "bags",
    subcategory: "clutch",
    price: 1180,
    currency: "USD",
    images: gallery(
      PHOTOS.clutch3,
      PHOTOS.clutch1,
      PHOTOS.clutch2,
      PHOTOS.clutch3,
      PHOTOS.clutch1,
      PHOTOS.clutch2
    ),
    colorImages: colorGalleries({
      gold: [PHOTOS.clutch3, PHOTOS.clutch1, PHOTOS.clutch2, PHOTOS.clutch3, PHOTOS.clutch1, PHOTOS.clutch2],
      black: [PHOTOS.clutch1, PHOTOS.clutch2, PHOTOS.clutch3, PHOTOS.clutch1, PHOTOS.clutch2, PHOTOS.clutch3],
    }),
    colors: [COLORS.gold, COLORS.black],
    sizes: [{ id: "os", label: "One Size", value: "OS", inStock: true }],
    variants: makeVariants(["OS"], [COLORS.gold, COLORS.black]),
    material: "Quilted lambskin, gold hardware",
    care: "Store in dust bag.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["bags", "evening"],
  },
  // ─── Additional Perfumes ──────────────────────────────
  {
    id: "34",
    slug: "sloane-eau-de-toilette",
    name: "Sloane Eau de Toilette",
    description: "Citrus, neroli, and cedar. A bright daytime composition in 100ml.",
    gender: "men",
    category: "perfumes",
    subcategory: "eau-de-toilette",
    price: 165,
    currency: "USD",
    images: gallery(
      PHOTOS.cologne2,
      PHOTOS.cologne1,
      PHOTOS.perfume3,
      PHOTOS.perfume2,
      PHOTOS.perfume1,
      PHOTOS.cologne2
    ),
    colorImages: colorGalleries({
      clear: [PHOTOS.cologne2, PHOTOS.cologne1, PHOTOS.perfume3, PHOTOS.perfume2, PHOTOS.perfume1, PHOTOS.cologne2],
    }),
    colors: [{ id: "clear", label: "Clear", value: "clear", inStock: true }],
    sizes: [{ id: "100", label: "100 ml", value: "100", inStock: true }],
    variants: [{ id: "100-clear", sku: "SR-EDT-100", size: "100", volumeMl: 100, priceModifier: 0, inStock: true }],
    material: "Eau de toilette, recyclable glass",
    care: "Store away from direct sunlight.",
    shippingNote: "Ships via certified fragrance courier.",
    tags: ["fragrance", "new"],
    isNew: true,
  },
  {
    id: "35",
    slug: "knightsbridge-bouquet",
    name: "Knightsbridge Floral Bouquet",
    description: "Rose, peony, and amber. A romantic eau de parfum in 75ml.",
    gender: "women",
    category: "perfumes",
    subcategory: "eau-de-parfum",
    price: 245,
    currency: "USD",
    images: gallery(
      PHOTOS.perfume2,
      PHOTOS.perfume3,
      PHOTOS.perfume1,
      PHOTOS.cologne1,
      PHOTOS.cologne2,
      PHOTOS.perfume2
    ),
    colorImages: colorGalleries({
      clear: [PHOTOS.perfume2, PHOTOS.perfume3, PHOTOS.perfume1, PHOTOS.cologne1, PHOTOS.cologne2, PHOTOS.perfume2],
    }),
    colors: [{ id: "clear", label: "Clear", value: "clear", inStock: true }],
    sizes: [
      { id: "50", label: "50 ml", value: "50", inStock: true },
      { id: "75", label: "75 ml", value: "75", inStock: true },
    ],
    variants: [
      { id: "50-clear", sku: "SR-KB-50", size: "50", color: "clear", volumeMl: 50, priceModifier: 0, inStock: true },
      { id: "75-clear", sku: "SR-KB-75", size: "75", color: "clear", volumeMl: 75, priceModifier: 80, inStock: true },
    ],
    material: "Eau de parfum, crystal flacon",
    care: "Keep capped between uses.",
    shippingNote: "Ships via certified fragrance courier.",
    tags: ["fragrance"],
  },
  {
    id: "36",
    slug: "belgravia-oud-extrait",
    name: "Belgravia Oud Extrait",
    description: "Saffron, oud, and leather. A deep evening extrait composed in Grasse.",
    gender: "women",
    category: "perfumes",
    subcategory: "extrait",
    price: 420,
    currency: "USD",
    images: gallery(
      PHOTOS.perfume3,
      PHOTOS.perfume1,
      PHOTOS.perfume2,
      PHOTOS.cologne2,
      PHOTOS.cologne1,
      PHOTOS.perfume3
    ),
    colorImages: colorGalleries({
      clear: [PHOTOS.perfume3, PHOTOS.perfume1, PHOTOS.perfume2, PHOTOS.cologne2, PHOTOS.cologne1, PHOTOS.perfume3],
    }),
    colors: [{ id: "clear", label: "Clear", value: "clear", inStock: true }],
    sizes: [{ id: "50", label: "50 ml", value: "50", inStock: true }],
    variants: [{ id: "50-clear", sku: "SR-OUD-50", size: "50", volumeMl: 50, priceModifier: 0, inStock: true }],
    material: "Extrait concentration, crystal flacon",
    care: "Store away from heat and light.",
    shippingNote: "Ships via certified fragrance courier.",
    tags: ["fragrance"],
  },
  {
    id: "37",
    slug: "mayfair-vetiver",
    name: "Mayfair Vetiver Eau de Parfum",
    description: "Vetiver, smoked tea, and tonka. A signature woody composition in 100ml.",
    gender: "men",
    category: "perfumes",
    subcategory: "eau-de-parfum",
    price: 220,
    currency: "USD",
    images: gallery(
      PHOTOS.cologne1,
      PHOTOS.perfume2,
      PHOTOS.cologne2,
      PHOTOS.perfume1,
      PHOTOS.perfume3,
      PHOTOS.cologne1
    ),
    colorImages: colorGalleries({
      clear: [PHOTOS.cologne1, PHOTOS.perfume2, PHOTOS.cologne2, PHOTOS.perfume1, PHOTOS.perfume3, PHOTOS.cologne1],
    }),
    colors: [{ id: "clear", label: "Clear", value: "clear", inStock: true }],
    sizes: [{ id: "100", label: "100 ml", value: "100", inStock: true }],
    variants: [{ id: "100-clear", sku: "SR-VET-100", size: "100", volumeMl: 100, priceModifier: 0, inStock: true }],
    material: "Eau de parfum, glass flacon",
    care: "Keep capped between uses.",
    shippingNote: "Ships via certified fragrance courier.",
    tags: ["fragrance"],
  },
  {
    id: "38",
    slug: "royal-bergamot-cologne",
    name: "Royal Bergamot Cologne",
    description: "Calabrian bergamot, lavender, and white musk. A fresh classical cologne.",
    gender: "men",
    category: "perfumes",
    subcategory: "cologne",
    price: 145,
    currency: "USD",
    images: gallery(
      PHOTOS.cologne2,
      PHOTOS.cologne1,
      PHOTOS.perfume1,
      PHOTOS.perfume2,
      PHOTOS.perfume3,
      PHOTOS.cologne2
    ),
    colorImages: colorGalleries({
      clear: [PHOTOS.cologne2, PHOTOS.cologne1, PHOTOS.perfume1, PHOTOS.perfume2, PHOTOS.perfume3, PHOTOS.cologne2],
    }),
    colors: [{ id: "clear", label: "Clear", value: "clear", inStock: true }],
    sizes: [{ id: "100", label: "100 ml", value: "100", inStock: true }],
    variants: [{ id: "100-clear", sku: "SR-BG-100", size: "100", volumeMl: 100, priceModifier: 0, inStock: true }],
    material: "Eau de cologne, recyclable glass",
    care: "Store in cool, dry place.",
    shippingNote: "Ships via certified fragrance courier.",
    tags: ["fragrance"],
  },
  // ─── Additional Accessories ───────────────────────────
  {
    id: "39",
    slug: "silk-pocket-square",
    name: "Hand-Rolled Silk Pocket Square",
    description: "Hand-rolled Italian silk pocket square in the House's signature print.",
    gender: "men",
    category: "accessories",
    subcategory: "pocket-square",
    price: 175,
    currency: "USD",
    images: gallery(
      PHOTOS.belt3,
      PHOTOS.belt1,
      PHOTOS.belt2,
      PHOTOS.accessoriesPromo,
      PHOTOS.cufflinks2,
      PHOTOS.cufflinks3
    ),
    colorImages: colorGalleries({
      navy: [PHOTOS.belt3, PHOTOS.belt1, PHOTOS.belt2, PHOTOS.accessoriesPromo, PHOTOS.cufflinks2, PHOTOS.cufflinks3],
      burgundy: [PHOTOS.belt1, PHOTOS.belt2, PHOTOS.belt3, PHOTOS.accessoriesPromo, PHOTOS.cufflinks3, PHOTOS.cufflinks2],
    }),
    colors: [COLORS.navy, COLORS.burgundy],
    sizes: [{ id: "os", label: "One Size", value: "OS", inStock: true }],
    variants: makeVariants(["OS"], [COLORS.navy, COLORS.burgundy]),
    material: "Italian silk, hand-rolled hem",
    care: "Dry clean only.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["accessories", "new"],
    isNew: true,
  },
  {
    id: "40",
    slug: "sapphire-cufflinks",
    name: "Sapphire Knot Cufflinks",
    description: "White gold knot cufflinks set with calibrated sapphire centres.",
    gender: "men",
    category: "accessories",
    subcategory: "cufflinks",
    price: 680,
    currency: "USD",
    images: gallery(
      PHOTOS.cufflinks3,
      PHOTOS.cufflinks1,
      PHOTOS.cufflinks2,
      PHOTOS.accessoriesPromo,
      PHOTOS.belt2,
      PHOTOS.belt3
    ),
    colorImages: colorGalleries({
      navy: [PHOTOS.cufflinks3, PHOTOS.cufflinks1, PHOTOS.cufflinks2, PHOTOS.accessoriesPromo, PHOTOS.belt2, PHOTOS.belt3],
      gold: [PHOTOS.cufflinks1, PHOTOS.cufflinks2, PHOTOS.cufflinks3, PHOTOS.accessoriesPromo, PHOTOS.belt3, PHOTOS.belt2],
    }),
    colors: [COLORS.navy, COLORS.gold],
    sizes: [{ id: "os", label: "One Size", value: "OS", inStock: true }],
    variants: makeVariants(["OS"], [COLORS.navy, COLORS.gold]),
    material: "White gold, sapphire",
    care: "Polish with a soft cloth.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["accessories"],
  },
  {
    id: "41",
    slug: "cashmere-scarf",
    name: "Mongolian Cashmere Scarf",
    description: "Lightweight cashmere scarf with hand-knotted fringe.",
    gender: "women",
    category: "accessories",
    subcategory: "scarf",
    price: 420,
    currency: "USD",
    images: gallery(
      PHOTOS.belt2,
      PHOTOS.belt1,
      PHOTOS.belt3,
      PHOTOS.accessoriesPromo,
      PHOTOS.belt2,
      PHOTOS.belt1
    ),
    colorImages: colorGalleries({
      cream: [PHOTOS.belt2, PHOTOS.belt1, PHOTOS.belt3, PHOTOS.accessoriesPromo, PHOTOS.belt2, PHOTOS.belt1],
      burgundy: [PHOTOS.belt1, PHOTOS.belt3, PHOTOS.belt2, PHOTOS.accessoriesPromo, PHOTOS.belt3, PHOTOS.belt1],
    }),
    colors: [COLORS.cream, COLORS.burgundy],
    sizes: [{ id: "os", label: "One Size", value: "OS", inStock: true }],
    variants: makeVariants(["OS"], [COLORS.cream, COLORS.burgundy]),
    material: "100% Mongolian cashmere",
    care: "Dry clean recommended.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["accessories", "new"],
    isNew: true,
  },
  {
    id: "42",
    slug: "grenadine-silk-tie",
    name: "Grenadine Silk Tie",
    description: "Hand-stitched grenadine silk tie with self-tipping and 9cm blade.",
    gender: "men",
    category: "accessories",
    subcategory: "tie",
    price: 195,
    currency: "USD",
    images: gallery(
      PHOTOS.belt1,
      PHOTOS.belt3,
      PHOTOS.belt2,
      PHOTOS.cufflinks1,
      PHOTOS.cufflinks2,
      PHOTOS.cufflinks3
    ),
    colorImages: colorGalleries({
      navy: [PHOTOS.belt1, PHOTOS.belt3, PHOTOS.belt2, PHOTOS.cufflinks1, PHOTOS.cufflinks2, PHOTOS.cufflinks3],
      burgundy: [PHOTOS.belt3, PHOTOS.belt1, PHOTOS.belt2, PHOTOS.cufflinks2, PHOTOS.cufflinks1, PHOTOS.cufflinks3],
    }),
    colors: [COLORS.navy, COLORS.burgundy],
    sizes: [{ id: "os", label: "One Size", value: "OS", inStock: true }],
    variants: makeVariants(["OS"], [COLORS.navy, COLORS.burgundy]),
    material: "Italian grenadine silk",
    care: "Roll loosely between wears.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["accessories"],
  },
  {
    id: "43",
    slug: "bridle-leather-belt",
    name: "Bridle Leather Dress Belt",
    description: "30mm dress belt in English bridle leather with brushed brass buckle.",
    gender: "men",
    category: "accessories",
    subcategory: "belts",
    price: 320,
    currency: "USD",
    images: gallery(
      PHOTOS.belt3,
      PHOTOS.belt2,
      PHOTOS.belt1,
      PHOTOS.cufflinks3,
      PHOTOS.cufflinks2,
      PHOTOS.cufflinks1
    ),
    colorImages: colorGalleries({
      black: [PHOTOS.belt3, PHOTOS.belt2, PHOTOS.belt1, PHOTOS.cufflinks3, PHOTOS.cufflinks2, PHOTOS.cufflinks1],
      burgundy: [PHOTOS.belt2, PHOTOS.belt1, PHOTOS.belt3, PHOTOS.cufflinks2, PHOTOS.cufflinks1, PHOTOS.cufflinks3],
    }),
    colors: [COLORS.black, COLORS.burgundy],
    sizes: ["80", "85", "90", "95", "100"].map((s) => ({ id: s, label: `${s} cm`, value: s, inStock: true })),
    variants: makeVariants(["80", "85", "90", "95", "100"], [COLORS.black, COLORS.burgundy]),
    material: "English bridle leather, brass buckle",
    care: "Condition twice yearly.",
    shippingNote: DEFAULT_SHIPPING,
    tags: ["accessories"],
  },
  ...CATALOG_ADDITIONS.map(hydrateCatalogProduct),
];

function hydrateCatalogProduct(product: Product): Product {
  if (product.variants.length > 0) return product;
  const sizes = product.sizes.map((s) => s.value);
  return {
    ...product,
    variants: makeVariants(sizes, product.colors),
  };
}

export const CATEGORY_LABELS: Record<ProductCategory, string> = {
  suits: "Suits & Tailoring",
  shoes: "Shoes",
  bags: "Bags",
  perfumes: "Perfumes",
  accessories: "Accessories",
};

export const CATEGORY_DESCRIPTIONS: Record<ProductCategory, string> = {
  suits:
    "Seven generations of cutting and tailoring on London's most storied street. From half-canvas ready-to-wear to fully bespoke morning coats, each suit is finished by hand in Mayfair with respect for tradition and an eye toward the present.",
  shoes:
    "A celebration of craftsmanship and character, Savile Row's shoes span timeless silhouettes and daring statements. From impeccably tailored dress shoes to bold sneakers and refined boots, each pair is crafted with precision and signature flair.",
  bags:
    "Heritage leather goods built to last a lifetime. From weekenders and briefcases for the road to evening clutches and structured totes, every bag is hand-cut and saddle-stitched using full-grain hides and solid brass hardware.",
  perfumes:
    "Compositions blended in Grasse and finished in London. The House's fragrances draw on the language of British perfumery — cologne, vetiver, oud, bergamot — interpreted with restraint and an unmistakable signature.",
  accessories:
    "The finishing touches of a well-considered wardrobe. Hand-rolled silk pocket squares, grenadine ties, English bridle belts, and precious-metal cufflinks — small objects built with the same exacting standards as the cloth they accompany.",
};

export const SUBCATEGORY_LABELS: Record<string, string> = {
  // suits
  "two-piece": "Two-Piece",
  "three-piece": "Three-Piece",
  tuxedo: "Tuxedos",
  "morning-coat": "Morning Coats",
  blazer: "Blazers",
  // shoes
  oxford: "Oxfords",
  loafer: "Loafers",
  "chelsea-boot": "Chelsea Boots",
  sneaker: "Sneakers",
  sandal: "Sandals",
  pump: "Pumps",
  boot: "Boots",
  // bags
  weekender: "Weekenders",
  clutch: "Clutches",
  tote: "Totes",
  briefcase: "Briefcases",
  crossbody: "Crossbody",
  backpack: "Backpacks",
  // perfumes
  "eau-de-parfum": "Eau de Parfum",
  cologne: "Cologne",
  "eau-de-toilette": "Eau de Toilette",
  extrait: "Extraits",
  // accessories
  cufflinks: "Cufflinks",
  belts: "Belts",
  wallets: "Wallets",
  "pocket-square": "Pocket Squares",
  scarf: "Scarves",
  tie: "Ties",
};

export const GENDER_LABELS: Record<Gender, string> = {
  women: "Women",
  men: "Men",
  kids: "Kids",
};

export function getAllProducts(): Product[] {
  return PRODUCTS.map(applyProductImages);
}

export function getProductBySlug(slug: string): Product | undefined {
  const p = PRODUCTS.find((item) => item.slug === slug);
  return p ? applyProductImages(p) : undefined;
}

export function getProductsByCollection(
  gender?: Gender,
  category?: ProductCategory
): Product[] {
  return PRODUCTS.filter((p) => {
    if (gender && p.gender !== gender) return false;
    if (category && p.category !== category) return false;
    return true;
  }).map(applyProductImages);
}

export function getSubcategoriesFor(
  gender?: Gender,
  category?: ProductCategory
): string[] {
  if (!category) return [];
  const seen = new Set<string>();
  for (const p of PRODUCTS) {
    if (p.category !== category) continue;
    if (gender && p.gender !== gender) continue;
    if (p.subcategory) seen.add(p.subcategory);
  }
  return Array.from(seen);
}

export function getImagesForColor(product: Product, color: string): string[] {
  return product.colorImages[color] ?? product.images;
}

export function getRelatedProducts(
  product: Product,
  limit = 8
): Product[] {
  return PRODUCTS.filter(
    (p) =>
      p.id !== product.id &&
      p.category === product.category &&
      p.gender === product.gender
  )
    .slice(0, limit)
    .map(applyProductImages);
}

export const MENU_PROMOS: Record<
  string,
  { href: string; image: string }
> = {
  Women: {
    href: "/collections/women/suits",
    image: PHOTOS.womenPromo,
  },
  Men: {
    href: "/collections/men/suits",
    image: PHOTOS.menPromo,
  },
  Kids: {
    href: "/collections/kids/suits",
    image: PHOTOS.kidsPromo,
  },
};

export const NAV_TREE: {
  label: string;
  href?: string;
  children?: { label: string; href: string }[];
}[] = [
  {
    label: "Latest Collections",
    children: [
      { label: "All products", href: "/collections/all/products" },
      { label: "New arrivals", href: "/collections/all/products" },
      { label: "Spring / Summer 2026", href: "/collections/men/suits" },
    ],
  },
  {
    label: "Women",
    children: [
      { label: "Suits & Tailoring", href: "/collections/women/suits" },
      { label: "Shoes", href: "/collections/women/shoes" },
      { label: "Bags", href: "/collections/women/bags" },
      { label: "Perfumes", href: "/collections/women/perfumes" },
      { label: "Accessories", href: "/collections/women/accessories" },
    ],
  },
  {
    label: "Men",
    children: [
      { label: "Suits & Tailoring", href: "/collections/men/suits" },
      { label: "Shoes", href: "/collections/men/shoes" },
      { label: "Bags", href: "/collections/men/bags" },
      { label: "Perfumes", href: "/collections/men/perfumes" },
      { label: "Accessories", href: "/collections/men/accessories" },
    ],
  },
  {
    label: "Kids",
    children: [
      { label: "Suits", href: "/collections/kids/suits" },
      { label: "Shoes", href: "/collections/kids/shoes" },
    ],
  },
  {
    label: "Bespoke",
    children: [
      { label: "Configure Your Suit", href: "/bespoke" },
      { label: "Book a Fitting", href: "/appointments" },
    ],
  },
  {
    label: "Services",
    children: [
      { label: "Appointments", href: "/appointments" },
      { label: "Shipping", href: "/policies/shipping" },
      { label: "Returns", href: "/policies/returns" },
      { label: "FAQ", href: "/policies/faq" },
    ],
  },
];
